Add information disclosure detail page, and fix others.
pj-pss/community-user-app pull request #54
Opened 2018-01-19 05:48 UTC by tsukahara-t

* Add information disclosure detail page.
* Change the page title for each link.

* Change page title on my health and monitoring.
* Replace scroll button text and profile items with i18n format.
* Change top text on slide menu.
* Fix icon style on information disclosure history page.

closes #53

2018-01-22 04:18 UTC, dixonsiu requested changes

2018-01-22 04:18 UTC, dixonsiu commented on src/html/js/user.js
> +    $("#viewInfoDisclosureDetail #pageTitle").html(i18next.t("profile." + type));
If you want the element to be translated dynamically, it is better to do the following.  

         $('#viewInfoDisclosureDetail #pageTitle')
              .attr('data-i18n', 'profile.'+ type)
              .localize();

2018-01-22 04:18 UTC, dixonsiu commented on src/html/js/user.js
> +    $("#viewInfoDisclosureDetail #pageTitle").html(i18next.t("profile." + type));
Any reason why you cannot use $('#pageTitle') which is supposed to be unique, too?

2018-01-23 02:55 UTC, atsX approved these changes

2018-01-23 02:55 UTC, merged