Acquire information and create screens.
pj-pss/community-user-app pull request #83
Opened 2018-03-05 02:14 UTC by wata47

Temporary design.
closes #81

2018-03-05 02:52 UTC, dixonsiu requested changes

2018-03-05 02:52 UTC, dixonsiu commented on src/html/entryList.html
> +<a href="javascript:view('articleDetail')" class="back_link"><span data-i18n="msg.backToBbs"></span></a>
onclick event?

2018-03-05 02:52 UTC, dixonsiu commented on src/html/js/user.js
> +function formatDate(date) {
Please use moment.js

2018-03-05 02:52 UTC, dixonsiu commented on src/html/js/user.js
> +	    var oData = 'test_reply';
Please use proper name even for prototype. You need to design the proper data structures (OData) first.

2018-03-06 00:15 UTC, atsX approved these changes

2018-03-06 00:15 UTC, merged